"""As-flown verification tests.

A synthetic sortie is generated by sampling the planned segments (track
points every ~15 m at the planned AMSL height, photos at the planned
exposure stations); individual tests then perturb the synthesis to
exercise deviation, gap, intrusion, margin and validation handling.
"""
import pytest

from drone_planner.app import create_app
from test_api import make_request

T0 = 1_700_000_000.0  # fixed epoch base keeps logs deterministic


@pytest.fixture()
def client(tmp_path):
    app = create_app(str(tmp_path / "test.db"))
    app.config.update(TESTING=True)
    return app.test_client()


def make_plan(client, **overrides):
    resp = client.post("/api/v1/plans", json=make_request(**overrides))
    assert resp.status_code == 201, resp.get_json()
    return resp.get_json()


def synth_flight(plan, *, seg_ids=None, lat_shift_deg=0.0, shift_seg_ids=None,
                 photo_alt_scale=None, battery_start=250.0, battery_end=180.0,
                 dt=5.0, drop_photo_ids=(), photo_id_prefix="IMG"):
    """Build an as-flown log following the plan's segments in flight order.

    ``lat_shift_deg`` moves the track/photos of ``shift_seg_ids`` (default:
    all chosen segments) north (the plan sweeps east-west lines with
    heading 0, so latitude is the cross-track direction).
    ``photo_alt_scale`` maps segment id -> AGL multiplier applied to that
    segment's photos only.
    """
    photo_alt_scale = photo_alt_scale or {}
    wanted = set(seg_ids) if seg_ids is not None else None
    if shift_seg_ids is None:
        shift_seg_ids = wanted if wanted is not None else {s["id"] for s in plan["segments"]}
    track, photos = [], []
    t = T0
    segs = [s for s in plan["segments"] if wanted is None or s["id"] in wanted]
    n_legs = sum(max(2, int(s["length_m"] // 15.0) + 1) for s in segs)
    leg_i = 0
    ph_i = 0
    for s in segs:
        (x0, y0), (x1, y1) = s["start"], s["end"]
        shift = lat_shift_deg if s["id"] in shift_seg_ids else 0.0
        n = max(2, int(s["length_m"] // 15.0) + 1)
        for k in range(n):
            f = k / (n - 1)
            frac = leg_i / max(1, n_legs - 1)
            track.append({
                "t": t,
                "pos": [x0 + (x1 - x0) * f, y0 + (y1 - y0) * f + shift],
                "alt_m": s["height_amsl_m"],
                "battery_wh": battery_start + (battery_end - battery_start) * frac,
            })
            t += dt
            leg_i += 1
        scale = photo_alt_scale.get(s["id"], 1.0)
        for k in range(s["photo_count"]):
            f = k / max(1, s["photo_count"] - 1)
            pid = f"{photo_id_prefix}_{ph_i:04d}"
            ph_i += 1
            if pid in drop_photo_ids:
                continue
            photos.append({
                "id": pid,
                "t": T0 + (t - T0) * 0.5 + k,  # inside the track time span
                "pos": [x0 + (x1 - x0) * f, y0 + (y1 - y0) * f + shift],
                "alt_m": s["height_amsl_m"] * scale,
                "attitude": {"roll_deg": 0.5, "pitch_deg": -0.4, "yaw_deg": 90.0},
            })
    photos.sort(key=lambda p: p["t"])
    return {"track": track, "photos": photos}


def verify(client, pid, flight, **extra):
    body = dict(flight)
    body.update(extra)
    return client.post(f"/api/v1/plans/{pid}/flights", json=body)


# --- happy path -------------------------------------------------------------

def test_clean_sortie_verifies(client):
    plan = make_plan(client, no_fly_zones=[])
    resp = verify(client, plan["plan_id"], synth_flight(plan))
    assert resp.status_code == 201, resp.get_json()
    data = resp.get_json()
    assert data["rules_version"]
    m = data["metrics"]
    assert m["coverage_pct"] > 95.0
    assert m["cross_track_max_m"] < 1.0
    assert m["exposure_gaps"] == 0
    assert m["nfz_intrusion_m"] == 0.0
    assert m["return_margin_ok"] is True
    assert m["gsd_breach_count"] == 0
    assert data["events"] == []
    assert data["first_event"] is None
    assert data["refly_segments"] == []
    assert data["uncovered_areas"] == []
    assert all(s["status"] == "flown" for s in data["segments"])
    # comparison against the plan
    cmp_ = data["comparison"]
    assert cmp_["coverage_pct"]["planned"] > 90.0
    assert abs(cmp_["coverage_pct"]["delta"]) < 5.0
    assert cmp_["energy_wh"]["actual"] == pytest.approx(250.0 - 180.0, abs=0.01)
    assert cmp_["photo_count"]["actual"] == m["photo_count"]
    assert cmp_["risk"]["actual"]["cross_track_deviations"] == 0


def test_gsd_and_spacing_reflect_terrain(client):
    plan = make_plan(client, no_fly_zones=[])
    data = verify(client, plan["plan_id"], synth_flight(plan)).get_json()
    m = data["metrics"]
    assert m["gsd_cm_min"] == pytest.approx(3.0, abs=0.05)
    assert m["gsd_cm_max"] > m["gsd_cm_min"]  # relief lowers AGL over valleys
    assert m["exposure_spacing_m"]["mean"] == pytest.approx(21.9, abs=3.0)
    assert m["forward_overlap_min"] > 0.5


# --- deviation / gaps / intrusion / margin ----------------------------------

def test_cross_track_deviation_flagged_in_time_order(client):
    plan = make_plan(client, no_fly_zones=[])
    ids = [s["id"] for s in plan["segments"]]
    shifted = set(ids[2:4])
    # ~22 m north: beyond the ~17 m default threshold, but still nearer to
    # the own line than to the adjacent one (spacing ~49 m)
    flight = synth_flight(plan, lat_shift_deg=0.0002, shift_seg_ids=shifted)
    resp = verify(client, plan["plan_id"], flight)
    assert resp.status_code == 201, resp.get_json()
    data = resp.get_json()
    dev_events = [e for e in data["events"] if e["type"] == "cross_track_deviation"]
    assert dev_events
    assert {e["segment_id"] for e in dev_events} == shifted
    assert data["first_event"] == data["events"][0]
    assert data["first_event"]["type"] == "cross_track_deviation"
    seg_report = {s["id"]: s for s in data["segments"]}
    for sid in shifted:
        assert seg_report[sid]["cross_track_max_m"] > 20.0
    assert data["metrics"]["points_beyond_threshold"] > 0


def test_early_return_leaves_segments_unflown(client):
    plan = make_plan(client, no_fly_zones=[])
    ids = [s["id"] for s in plan["segments"]]
    flown = ids[: max(2, len(ids) // 3)]
    flight = synth_flight(plan, seg_ids=flown, battery_start=250.0, battery_end=230.0)
    data = verify(client, plan["plan_id"], flight).get_json()
    seg_report = {s["id"]: s for s in data["segments"]}
    assert all(seg_report[i]["status"] == "flown" for i in flown)
    assert all(seg_report[i]["status"] == "not_flown" for i in ids if i not in flown)
    refly_ids = {r["id"] for r in data["refly_segments"]}
    assert set(ids) - set(flown) <= refly_ids
    assert set(flown).isdisjoint(refly_ids)
    m = data["metrics"]
    assert m["segments_not_flown"] == len(ids) - len(flown)
    assert m["uncovered_count"] > 0
    assert data["uncovered_areas"][0]["area_m2"] > 1.0
    cmp_ = data["comparison"]
    assert cmp_["coverage_pct"]["delta"] < 0.0
    assert cmp_["distance_m"]["delta"] < 0.0
    assert cmp_["energy_wh"]["delta"] < 0.0


def test_dropped_photos_cause_exposure_gap(client):
    plan = make_plan(client, no_fly_zones=[])
    probe = synth_flight(plan)
    # drop six consecutive triggers on the first segment -> spacing ~150 m
    # exceeds the ~109 m footprint length
    seg0 = plan["segments"][0]["id"]
    ids = [p["id"] for p in probe["photos"]]
    drop = set(ids[3:9])
    flight = synth_flight(plan, drop_photo_ids=drop)
    data = verify(client, plan["plan_id"], flight).get_json()
    gaps = [e for e in data["events"] if e["type"] == "exposure_gap"]
    assert gaps, "expected an exposure gap from dropped triggers"
    assert gaps[0]["segment_id"] == seg0
    affected = {p["id"]: p for p in data["affected_photos"]}
    assert gaps[0]["photo_id"] in affected
    assert "exposure_gap" in affected[gaps[0]["photo_id"]]["issues"]
    assert data["metrics"]["exposure_gaps"] >= 1
    refly = {r["id"]: r["reasons"] for r in data["refly_segments"]}
    assert "exposure_gap" in refly.get(seg0, [])


def test_high_flying_photos_breach_gsd(client):
    plan = make_plan(client, no_fly_zones=[])
    seg = plan["segments"][1]["id"]
    flight = synth_flight(plan, photo_alt_scale={seg: 1.4})
    data = verify(client, plan["plan_id"], flight).get_json()
    assert data["metrics"]["gsd_breach_count"] > 0
    breached = [p for p in data["affected_photos"] if "gsd_breach" in p["issues"]]
    assert breached
    assert all(p["segment_id"] == seg for p in breached)
    assert all(p["gsd_cm"] > 3.0 * 1.15 for p in breached)


def test_nfz_crossing_track_is_flagged(client):
    plan = make_plan(client)  # default request includes the NFZ band
    data = verify(client, plan["plan_id"], synth_flight(plan)).get_json()
    intrusions = [e for e in data["events"] if e["type"] == "nfz_intrusion"]
    assert intrusions, "connectors across the NFZ band must be flagged"
    assert data["metrics"]["nfz_intrusion_m"] > 0.5
    assert data["comparison"]["risk"]["actual"]["nfz_intrusions"] == 1


def test_low_battery_flags_return_margin(client):
    plan = make_plan(client, no_fly_zones=[])
    flight = synth_flight(plan, battery_start=80.0, battery_end=15.0)
    data = verify(client, plan["plan_id"], flight).get_json()
    events = [e for e in data["events"] if e["type"] == "return_margin_low"]
    assert events, "expected a return-margin event"
    assert data["metrics"]["return_margin_ok"] is False
    assert data["metrics"]["return_margin_min_wh"] < 0.0


# --- validation --------------------------------------------------------------

def test_track_time_order_and_missing_data_rejected(client):
    plan = make_plan(client, no_fly_zones=[])
    flight = synth_flight(plan)
    pid = plan["plan_id"]

    swapped = dict(flight)
    swapped["track"] = [dict(p) for p in flight["track"]]
    swapped["track"][5], swapped["track"][6] = swapped["track"][6], swapped["track"][5]
    resp = verify(client, pid, swapped)
    assert resp.status_code == 400
    assert any("time order" in e or "increasing" in e for e in resp.get_json()["errors"])

    nulled = dict(flight)
    nulled["track"] = [dict(p) for p in flight["track"]]
    nulled["track"][3]["alt_m"] = None
    resp = verify(client, pid, nulled)
    assert resp.status_code == 400
    assert any("track[3].alt_m" in e for e in resp.get_json()["errors"])

    missing_att = dict(flight)
    missing_att["photos"] = [dict(p) for p in flight["photos"]]
    del missing_att["photos"][0]["attitude"]
    resp = verify(client, pid, missing_att)
    assert resp.status_code == 400
    assert any("attitude" in e for e in resp.get_json()["errors"])


def test_unit_checks(client):
    plan = make_plan(client, no_fly_zones=[])
    flight = synth_flight(plan)
    pid = plan["plan_id"]

    # battery in percent instead of Wh
    pct = dict(flight)
    pct["track"] = [dict(p, battery_wh=95.0) for p in flight["track"]]
    resp = verify(client, pid, pct)
    assert resp.status_code == 201  # 95 Wh is plausible; monotonic ok
    # battery far above the nominal pack -> unit error
    over = dict(flight)
    over["track"] = [dict(p, battery_wh=9999.0) for p in flight["track"]]
    resp = verify(client, pid, over)
    assert resp.status_code == 400
    assert any("battery_wh" in e for e in resp.get_json()["errors"])

    # altitude a hundredfold off (e.g. centimetres) -> outside the AMSL range
    hundredfold = dict(flight)
    hundredfold["track"] = [dict(p, alt_m=p["alt_m"] * 100.0) for p in flight["track"]]
    resp = verify(client, pid, hundredfold)
    assert resp.status_code == 400
    assert any("alt_m" in e for e in resp.get_json()["errors"])

    # AGL submitted as AMSL -> far below the hill terrain (datum confusion)
    agl_only = dict(flight)
    agl_only["track"] = [dict(p, alt_m=109.44) for p in flight["track"]]
    resp = verify(client, pid, agl_only)
    assert resp.status_code == 400
    assert any("below terrain" in e for e in resp.get_json()["errors"])

    # timestamps in 100 ms units -> implied speed far too high
    fast = dict(flight)
    fast["track"] = [dict(p, t=T0 + i * 0.1) for i, p in enumerate(flight["track"])]
    fast["photos"] = []  # keep trigger times out of the way of the speed check
    resp = verify(client, pid, fast)
    assert resp.status_code == 400
    assert any("implied speed" in e for e in resp.get_json()["errors"])

    # battery increasing mid-flight
    up = dict(flight)
    up["track"] = [dict(p) for p in flight["track"]]
    up["track"][10]["battery_wh"] = up["track"][0]["battery_wh"] + 5.0
    resp = verify(client, pid, up)
    assert resp.status_code == 400
    assert any("battery_wh" in e for e in resp.get_json()["errors"])


def test_crs_and_structure_validation(client):
    plan = make_plan(client, no_fly_zones=[])
    flight = synth_flight(plan)
    pid = plan["plan_id"]

    assert verify(client, pid, flight, crs="EPSG:foo").status_code == 400
    assert verify(client, pid, {"track": [], "photos": []}).status_code == 400
    assert verify(client, pid, {"photos": []}).status_code == 400
    assert verify(client, pid, {"track": flight["track"]}).status_code == 400

    # flight log in UTM 50N while the plan is in EPSG:4326
    from pyproj import Transformer
    fwd = Transformer.from_crs("EPSG:4326", "EPSG:32650", always_xy=True)
    utm = {
        "crs": "EPSG:32650",
        "track": [dict(p, pos=list(fwd.transform(*p["pos"]))) for p in flight["track"]],
        "photos": [dict(p, pos=list(fwd.transform(*p["pos"]))) for p in flight["photos"]],
    }
    resp = verify(client, pid, utm)
    assert resp.status_code == 201, resp.get_json()
    assert resp.get_json()["metrics"]["cross_track_max_m"] < 1.0


def test_photo_time_outside_track_rejected(client):
    plan = make_plan(client, no_fly_zones=[])
    flight = synth_flight(plan)
    flight["photos"][0]["t"] = T0 - 7200.0
    resp = verify(client, plan["plan_id"], flight)
    assert resp.status_code == 400
    assert any("time span" in e for e in resp.get_json()["errors"])


# --- audit: persistence, replay, geojson ------------------------------------

def test_flight_is_stored_listed_and_replayed(client):
    plan = make_plan(client, no_fly_zones=[])
    created = verify(client, plan["plan_id"], synth_flight(plan)).get_json()
    fid = created["flight_id"]

    listing = client.get(f"/api/v1/plans/{plan['plan_id']}/flights").get_json()
    assert any(f["id"] == fid for f in listing["flights"])
    assert listing["flights"][0]["rules_version"]

    fetched = client.get(f"/api/v1/flights/{fid}")
    assert fetched.status_code == 200
    assert fetched.get_json()["metrics"] == created["metrics"]

    replay = client.post(f"/api/v1/flights/{fid}/replay")
    assert replay.status_code == 200
    data = replay.get_json()
    assert data["metrics_match"] is True
    assert data["events_match"] is True
    assert data["geojson_match"] is True
    assert data["stored_rules_version"] == data["current_rules_version"]


def test_flight_geojson_report(client):
    plan = make_plan(client)
    created = verify(client, plan["plan_id"], synth_flight(plan)).get_json()
    resp = client.get(f"/api/v1/flights/{created['flight_id']}/geojson")
    assert resp.status_code == 200
    fc = resp.get_json()
    assert fc["type"] == "FeatureCollection"
    kinds = {f["properties"]["feature"] for f in fc["features"]}
    assert {"survey_area", "no_fly_zone", "planned_segment", "track",
            "photo", "event", "home"} <= kinds
    statuses = {
        f["properties"]["status"] for f in fc["features"]
        if f["properties"]["feature"] == "planned_segment"
    }
    assert statuses == {"flown"}


def test_unknown_flight_ids(client):
    assert client.get("/api/v1/flights/nope").status_code == 404
    assert client.get("/api/v1/flights/nope/geojson").status_code == 404
    assert client.post("/api/v1/flights/nope/replay").status_code == 404
    assert client.post("/api/v1/flights/nope/reflight", json={}).status_code == 404
    assert client.get("/api/v1/plans/nope/flights").status_code == 404
    assert client.post("/api/v1/plans/nope/flights", json={}).status_code == 404


# --- reflight ----------------------------------------------------------------

def test_reflight_locks_qualified_segments(client):
    plan = make_plan(client, no_fly_zones=[])
    ids = [s["id"] for s in plan["segments"]]
    flown = ids[: max(2, len(ids) // 3)]
    flight = verify(
        client, plan["plan_id"], synth_flight(plan, seg_ids=flown)
    ).get_json()

    resp = client.post(f"/api/v1/flights/{flight['flight_id']}/reflight", json={})
    assert resp.status_code == 201, resp.get_json()
    data = resp.get_json()
    assert data["parent_id"] == plan["plan_id"]
    # default lock = every segment the verification did not flag
    assert set(data["locked_segment_ids"]) == set(flown)
    assert data["metrics"]["num_frozen"] == len(flown)
    frozen = [s for s in data["segments"] if s["frozen"]]
    assert {s["id"] for s in frozen} == set(flown)
    # the reflight plan re-sweeps the missed area
    assert data["metrics"]["num_segments"] > len(flown)
    assert data["metrics"]["coverage_pct"] > 90.0

    cmp_resp = client.get(
        f"/api/v1/plans/{plan['plan_id']}/compare/{data['plan_id']}"
    )
    assert cmp_resp.status_code == 200


def test_reflight_warns_when_locking_flagged_segment(client):
    plan = make_plan(client, no_fly_zones=[])
    ids = [s["id"] for s in plan["segments"]]
    flown = ids[: max(2, len(ids) // 3)]
    flight = verify(
        client, plan["plan_id"], synth_flight(plan, seg_ids=flown)
    ).get_json()
    fid = flight["flight_id"]
    flagged = flight["refly_segments"][0]["id"]

    resp = client.post(
        f"/api/v1/flights/{fid}/reflight",
        json={"locked_segment_ids": flown + [flagged]},
    )
    assert resp.status_code == 201
    assert resp.get_json()["warnings"]

    resp = client.post(
        f"/api/v1/flights/{fid}/reflight",
        json={"locked_segment_ids": ["S999"]},
    )
    assert resp.status_code == 400
